### ISSUE TITLE
Generating sample segments of audio recordings

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#111]
This depends on some parts of #64 - progress and datasets.

The idea is to create (seeded) random and algorithm-specified smaller segments of audio from long audio recordings. This is for giving people much smaller sets of recordings to annotate.

Two types of sampling:
- random, with optional seed
- algorithm, based on prior knowledge about spread of faunal vocalisations

First iteration will have three parameters:
- audio recording id
- number of 1 minute samples to return (1 minute is QutBioacoustics standard)
-  optional seed for randomness

Future iterations:
- algorithm for selecting segments based on desired outcome of annotation

**Comment by atruskie** [comment]
This idea has been superseded by #347  - but good news! It is actually on its way to being implemented.
