### ISSUE TITLE
Filter API not working

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#145]
HTTP POST to `staging.ecosounds.org/sites/filter`

With content:

```
{
  "filter": {
    "projectIds": {
      "in": ["397"]
      }
    }
 }
```

Fails with:

```
{
    "meta": {
        "status": 400,
        "message": "Bad Request",
        "error": {
            "details": "Filter parameters were not valid: Must be a collection of items, got Arel::SelectManager."
        }
    },
    "data": null
}

```

**Comment by cofiem** [comment]
See https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/filter/validate.rb#L179

Issue seems to be that the more restricted `in` validation does not allow for `Arel::SelectManager`.

Don't forget to make a test!

**Comment by cofiem** [comment]
A similar issue is occurring with the `/audio_events/filter` endpoint. I don't know if it's the same cause, as error messages have been made more vague since this issue. However, it is a `POST` with only an `id` filter, and the response is a `404`.

More details to follow.
