### ISSUE TITLE
Bug with annotation library filter.

### ISSUE THREAD

**Issue by antmt** [QutBioacoustics/baw-server#148]
See:
"\ownCloud\Shared\Ecoacoustics\Ecosounds\Issues\annotation_library-request.har"

It seems the `tags_partial` QSP has no effect on query results for `GET /audio_events/library/paged?page=1&reference=true&tags_partial=bittern&tags_partial=koala`

Blocking  to QutBioacoustics/baw-client#168

**Comment by antmt** [comment]
Bug producible without duplicate QSP as well:

`GET http://staging.ecosounds.org/audio_events/library/paged?page=1&reference=true&tags_partial=bittern`

returns:

```
...
        {
            "audio_event_id": 124595,
            "id": 124595,
            "audio_event_start_date": "2012-10-20T06:00:06.037+10:00",
            "audio_recording_id": 234234,
            "audio_recording_duration_seconds": "7199.004",
            "audio_recording_recorded_date": "2012-10-20T06:00:00.000+10:00",
            "site_name": "NE",
            "site_id": 398,
            "owner_name": "anthony",
            "owner_id": 9,
            "is_reference": true,
            "start_time_seconds": "6.0372",
            "end_time_seconds": "9.3576",
            "high_frequency_hertz": "2239.4531",
            "low_frequency_hertz": "947.4609",
            "updated_at": "2014-12-11T20:39:14.073+10:00",
            "updater_id": 9,
            "created_at": "2013-12-15T17:09:18.343+10:00",
            "creator_id": 9,
            "tags": [
                {
                    "id": 113,
                    "text": "Lewin's Rail",
                    "is_taxanomic": true,
                    "retired": false,
                    "type_of_tag": "common_name"
                },
                {
                    "id": 112,
                    "text": "Lewin's Honeyeater",
                    "is_taxanomic": true,
                    "retired": false,
                    "type_of_tag": "common_name"
                }
            ],
            "projects": [
                {
                    "id": 469,
                    "name": "FGCS Ref"
                },
                {
                    "id": 397,
                    "name": "SERF Acoustic Study"
                }
            ],
...
```

**Comment by cofiem** [comment]
I've found the problem - the expected QSP is tagsPartial. It doesn't account for camel case vs snake case. This is a small fix I can do.

**Comment by cofiem** [comment]
A side note - this url seems to better fit the intention: `GET /audio_events/library/paged?page=1&reference=true&tags_partial=bittern,koala`

**Comment by antmt** [comment]
I worked out what caused this - I introduced a change the snake_cased QSP object as well in https://github.com/QutBioacoustics/baw-client/commit/8069254805f1c4bde0b645b7920521fa8f9c9fae

In theory  baw-server should not have to worry about camelCased QSPs anymore.

And again, IGNORE the duplicate QSP!
