### ISSUE TITLE
PG Syntax Error

### ISSUE THREAD

**Issue by alvinsw** [QutBioacoustics/baw-server#150]
I received multiple exception emails from the baw-server, that can be categorised into three different errors:

### 1.  audio_recordings#filter
An ActiveRecord::StatementInvalid occurred in audio_recordings#filter:

  PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ...io_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10...
                                                             ^
: SELECT COUNT(*) FROM "audio_recordings"  WHERE ("audio_recordings"."deleted_at" IS NULL) AND "audio_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10, 11, 12)
  lib/modules/api/response.rb:217:in `add_paging_and_sorting'

Request:
  * URL        : http://baw.dev.bush.fm/audio_recordings/filter
  * HTTP Method: POST
  * IP address : 129.127.180.186
  * Parameters : {"paging"=>{"items"=>10, "page"=>1}, "projection"=>{"include"=>["id", "siteId", "durationSeconds", "recordedDate", "createdAt"]}, "sorting"=>{"orderBy"=>"createdAt", "direction"=>"desc"}, "format"=>"json", "controller"=>"audio_recordings", "action"=>"filter", "audio_recording"=>{}}

### 2. user_accounts#audio_events

An ActionView::Template::Error occurred in user_accounts#audio_events:

  PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ...io_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10...
                                                             ^
: SELECT DISTINCT COUNT(DISTINCT "audio_events"."id") FROM "audio_events"  WHERE ("audio_events"."deleted_at" IS NULL) AND "audio_events"."audio_recording_id" IN (SELECT "audio_recordings"."id" FROM "audio_recordings"  WHERE ("audio_recordings"."deleted_at" IS NULL) AND "audio_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10, 11, 12))
  app/views/user_accounts/audio_events.html.haml:9:in `_app_views_user_accounts_audio_events_html_haml___911526360752883964_70732160'

Request:
  * URL        : http://baw.dev.bush.fm/user_accounts/5/audio_events
  * HTTP Method: GET
  * IP address : 129.127.180.186
  * Parameters : {"action"=>"audio_events", "controller"=>"user_accounts", "id"=>"5"}

### 3. audio_event_comments#index
An ActiveRecord::StatementInvalid occurred in audio_event_comments#index:

  PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ...io_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10...
                                                             ^
: SELECT COUNT(*) FROM "audio_event_comments"  WHERE ("audio_event_comments"."deleted_at" IS NULL) AND "audio_event_comments"."audio_event_id" IN (SELECT "audio_events"."id" FROM "audio_events"  WHERE ("audio_events"."deleted_at" IS NULL) AND "audio_events"."audio_recording_id" IN (SELECT "audio_recordings"."id" FROM "audio_recordings"  WHERE ("audio_recordings"."deleted_at" IS NULL) AND "audio_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10, 11, 12)))
  lib/modules/api/response.rb:217:in `add_paging_and_sorting'

Request:
  * URL        : http://baw.dev.bush.fm/audio_events/26/comments
  * HTTP Method: GET
  * IP address : 129.127.180.186
  * Parameters : {"format"=>"json", "action"=>"index", "controller"=>"audio_event_comments", "audio_event_id"=>"26"}

**Comment by atruskie** [comment]
@cofiem has suggested that somehow you've managed to create a site will a null id.

Can you run this SQL against your DB to confirm?

```
SELECT * FROM sites WHERE id is NULL
```

**Comment by cofiem** [comment]
Also, I think these are all the result of the same bug. From my previous investigations and the backtraces, this is the place to start looking: `lib/modules/api/response.rb:217`. Combining that with the query used in `app/views/user_accounts/audio_events.html.haml:9` should give a hint as to the problem.

**Comment by cofiem** [comment]
Problem located in common code in [`app/models/user.rb:170`](https://github.com/QutBioacoustics/baw-server/blob/0.12.1/app/models/user.rb#L170)

    user_sites = self.projects.map { |project| project.sites.map { |site| site.id } }.to_a.uniq

Somehow `user_sites` ends up with `nil`s, which is then used in subsequent queries:

    "audio_recordings"."site_id" IN (3, 2, 5, 4, 6, 7, 8, , 1, 9, 10, 11, 12)

A quick fix would be to add `.compact`. Would be better to find the source of the problem.

@alvinsw can you add `.compact` to the end of line 170 in `/app/models/user.rb` to see if that fixes the errors?

**Comment by cofiem** [comment]
Could also try `.reject(&:empty?)` instead of `.compact` if the problem is empty strings rather than `nil`s. I can't seem to reproduce this error.

**Comment by alvinsw** [comment]
`SELECT * FROM sites WHERE id is NULL` returns nothing. However, I checked all the entries from that table and one of the record has empty unpdater_id. For example:
id;name;longitude;latitude;notes;creator_id;updater_id
1;"Karawatha";153.080093;-27.631731;"";1;1
3;"Secondary (Savanna)";133.600000;-22.290000;"";5;
2;"Core Plot (Mulga)";133.300000;-22.280000;"";5;5
4;"Cumberland 1";150.738209;-33.619017;"";1;2
...
There are 12 sites in total with id exactly ranging from 1 to 12, and nothing is missing in between.

**Comment by atruskie** [comment]
The `null` `updater_id` is expected behaviour for a record that has been created but never updated again - it is not your problem.

I'd suggest trying @cofiem's suggestions next

**Comment by alvinsw** [comment]
Adding `.reject(&:empty?)` seems to fix the error. But should we investigate further on why the

    self.projects.map { |project| project.sites.map { |site| site.id } }.to_a.uniq

is able to produce `(3, 2, 5, 4, 6, 7, 8, , 1, 9, 10, 11, 12)` in the first place?

**Comment by atruskie** [comment]
Also - since we can't reproduce this problem - we still think it might be a database consistency problem.

You haven't accidently deleted a `site` with pqsql? Rather than through the website?

Can you run the following queries against your database (the output should be the same):

```sql
SELECT s.id, ar.site_id AS audio_recording_site_id
FROM sites s
FULL OUTER JOIN ( 
	SELECT DISTINCT(site_id)
	FROM audio_recordings
) ar ON s.id = ar.site_id
ORDER BY s.id
```

```sql
SELECT s.id, ps.site_id AS projects_sites_site_id
FROM sites s
FULL OUTER JOIN ( 
	SELECT DISTINCT(site_id)
	FROM projects_sites
) ps ON s.id = ps.site_id
ORDER BY s.id
```

For either query we are testing to see if another table has a reference to a site that no longer exists. For both queries, when you run them, there should be *NO* nulls in the first column, but there may be nulls in the second column.

**Comment by alvinsw** [comment]
No, I have not done any direct modification to the pgsql.
Result from the first query:

    1;1
    2;2
    3;
    4;4
    5;5
    6;6
    7;7
    8;8
    9;9
    10;10
    11;11
    12;12

Result from second query:

    1;1
    2;2
    3;3
    4;4
    5;5
    6;6
    7;7
    8;8
    9;9
    10;10
    11;11
    12;12

**Comment by atruskie** [comment]
Hmmm... 
I'm stumped. @cofiem any idea?

Alvin, I think you need to debug this... set a breakpoint and step through the execution.

We really need to be able to reproduce this issue.

Alvin what would be amazing is if you could write a unit test that demonstrated the bug - that's the usual method of fixing bugs in rails/open source projects.

**Comment by cofiem** [comment]
For diagnostic purposes, try this. Change this line

    user_sites = self.projects.map { |project| project.sites.map { |site| site.id } }.to_a.uniq

to
```
user_sites = self.projects.map { |project|
      fail 'One or more sites were blank.' if project.sites.any? { |site| site.nil? }

      sites_array = project.site_ids
      fail 'One or more site ids were nil.' if sites_array.any? { |id| id.nil? }

      sites_array
    }.flatten
```

This will check for blank sites and nil site ids, as well as making use of the built-in site_ids method rather than multiple `map`s.

**Comment by cofiem** [comment]
Hi @alvinsw, have you had a chance to try out the changes for diagnosing the problem?

There's a new release that includes these changes: https://github.com/QutBioacoustics/baw-server/releases/tag/0.13.1

**Comment by cofiem** [comment]
Hi @alvinsw there's another new release you could try: https://github.com/QutBioacoustics/baw-server/releases/tag/0.14.0

**Comment by cofiem** [comment]
Haven't heard anything for this issue in a while. Closing for now. Please comment or re-open if needed.
