### ISSUE TITLE
Bug with inserting tags with new audio events based on case sensitivity

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#166]
This line: https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/audio_event.rb#L315

Is causing problems. A case-insensitive query needs to be done.

And:
https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/audio_event.rb#L321

also needs to be changed to case-insensitive compare.

Additional issue:
The error that occurs when it saves, it seems to be trying to insert information from audio_events table into the audio_events_tags table
Related to this line: https://github.com/QutBioacoustics/baw-server/blob/develop/app/controllers/audio_events_controller.rb#L82

**Comment by cofiem** [comment]
Case issue is closed. Other issue is here #174
