### ISSUE TITLE
fix(media) Suggestion: handle well known resque errors better

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#168]
For example: for a file not found error thrown by a resque worker, a generic 500 is returned from the API, whereas as a 400 is much more reasonable.

Thus, some well-known resque errors should be handled and special cases appropriately - with  unexpected/generic exceptions still handled as they are now (returning 500s).

**Comment by cofiem** [comment]
The message in the error is not useful due to this line: https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/media_poll.rb#L65

Check to see if the error is caught and raised and caught again - which would be why two error emails are sent.

**Comment by cofiem** [comment]
Raise a custom error that can be dealt with specificly

https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/media_poll.rb#L178
