### ISSUE TITLE
Change baw.ecosounds.org subdomain

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#179]
Despite the sheer irrelevance we need to change the sub-domain

Work items:

 - [ ] DNS update
 - [ ] Settings files?
 - [ ] Hard coded files?
 - [ ] Others?

@cofiem help?

**Comment by cofiem** [comment]
Also need to check in other repos, including private repos.

**Comment by cofiem** [comment]
See https://github.com/QutBioacoustics/baw-private/issues/80
