### ISSUE TITLE
Overlap check is not acting as intended

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#184]
`overlap_amount=>0.003`

**Comment by cofiem** [comment]
Server is reporting overlap for files that do not actually overlap:

For example:

existing: 
 - start Wed, 22 Oct 2014 20:01:00 AEST +10:00, 
 - end Wed, 22 Oct 2014 22:01:00 AEST +10:00, 
 - duration 7200.003 seconds

new:
 - start 2014-10-23T00:01:00.000+10:00
 - end 2014-10-23T00:03:00.000+10:00
 - duration 7200.003

Reports overlap of 0.003, "start of new, end of existing".

Two problems:
 - these starts and ends do not overlap
 - the overlap amount is under the threshold, even if they did overlap, and should be modified.

**Comment by atruskie** [comment]
:+1:

**Comment by cofiem** [comment]
Overlap check works as intended, but the overlap is not being fixed.

Places to investigate:
 - https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/audio_recording_overlap.rb#L241
 - https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/audio_recording.rb#L292

**Comment by cofiem** [comment]
Decision is to get rid of validations, and do all checks in `create` action. This should be fine, since audio_recordings are not modified once created (apart from via the harvester, which this will cater for).
