### ISSUE TITLE
Bad sample rate validations in .../media

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#187]
`GET http://baw.ecosounds.org/audio_recordings/192375/media.png?end_offset=60&start_offset=30&sample_rate=22050user_token=IAMANAUTHTOKEN`

Generates a resque request that fails. Note the missing ampersand for the last QSP.

Theory: sample_rate check not done until resque uses audio workers code. It should be done before job is issued.

**Comment by atruskie** [comment]
Basic DX reveals that the invalid parameter is being passed right through to SOX

`sox FAIL rate: usage: [-q|-l|-m|-h|-v] [`...

**Comment by cofiem** [comment]
turns out the issue is:

    '22050user_token=IAMANAUTHTOKEN'.to_i == 22050

More robust value checking required...
