### ISSUE TITLE
Provide an API endpoint for viewing results of job

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#196]
TODO: spec out

Related to:
https://github.com/QutBioacoustics/baw-private/issues/83

https://github.com/QutBioacoustics/baw-server/issues/193

**Comment by cofiem** [comment]
Route: /jobs/1/results

Response:
 - folder structure?
 - filter by file type?
 - json metadata
 - describe what the files are for?
 - approximate csv length based on file size?
 - ability for server to seek into csv files?
 - 'simplified' access to common files?
    - e.g. /jobs/1/results/false_colour/20150510T220000
    - e.g. /jobs/1/results/events/85000 (offset from start of audio file in events file for the analysis type)
    - e.g. /jobs/1/results/events/20150510T220000 (absolute time in events file for the analysis type)
    - e.g. /jobs/1/results/indices/20150510T220000 (absolute time in indices file for the analysis type)
 - additional processing to get a 'summary' csv for information required by website?

**Comment by atruskie** [comment]
Initial spec calls only for very basic file access.

It will basically expose files. Route will need to be extendable for full path seeking...
either 
/jobs/1/results/Towsey.Acoustic/ACI.csv
or
/jobs/1/results?file=/Towsey.Acoustic/ACI.csv

I'd even seriously think about exposing the results folders as rails static file locations.

The other features we've talked about, but should be specced out in the next milestone

**Comment by atruskie** [comment]
Also, JSON response for getting a directory (e.g. `/jobs/1/results/Towsey.Acoustic/`) should be just a list of files in directory

**Comment by atruskie** [comment]
Just a side note: whatever solution we choose for exposing files here, we should also factor out so the functionality is shared with the `audio_recordings/{id}/analysis.{extension}` end point (i.e. system analysis jobs)

**Comment by cofiem** [comment]
I'm a little confused - `/jobs` and `/audio_recordings/:id/analysis.:format` essentially do the same thing? What's the difference?

**Comment by atruskie** [comment]
Their functionality will be the same (I.e. Allowing access to files on disk) but the way the data is stored is really different.

Analysis_results (from custom jobs) are stored in job folders and are nested under /jobs

System analysis results more simply overwrite existing results. We currently have an endpoint for them nested under /audio_recordings (since when they were made there was no /jobs endpoint  and it doesn't make sense to nest then under jobs anyway)

**Comment by cofiem** [comment]
Currently recursive when it should not be.
