### ISSUE TITLE
Create saved_search model

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#199]
Related: #189 #64 #194 #198 #195

This essentially replaces the dataset model.

This model saves a query filter as `json`. 

It is owned by a user, and available to all users who have access to the projects referenced by the query filter. This is determined when the saved search is created. This may require an additional field, and may be instead of a `(custom_)jobs_projects` table (more generic). See #195.

Only create and delete (archive) are available. Immutable. Can be cloned to create a 'modified' saved_search.

`saved_search`:
 - id (int, primary)
 - creator_id (int, user id)
 - created_at (datetime)
 - updater_id (int, user id)
 - updated_at (datetime)
 - deleter_id (int, user id)
 - deleted_at (datetime)
 - stored_query (text, serialize as json to get postgres benefits, [rails setup](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html))
 - name (string)
 - description (long string)
 - others?

`projects_saved_searches`:
 - project_id (int)
 - saved_search_id (int)
 - others?

**Comment by atruskie** [comment]
An interesting approach to place the link to projects in `projects_saved_searches`. Certainly more generic than `projects_jobs`, has potential for reuse. I see users being able to share 'searches' so they can show particular sets of data.

Of course the query will need to be executed before this table (projects_saved_searches) can be populated, whereas with the jobs relation, the query was already being executed anyway. We just doubled the querying work.

Schema seems fine.
