### ISSUE TITLE
Modify the annotation download functionality to do a flat set of results

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#204]
We have a flat version of the annotation export in baw-private.

We should adapt this endpoint to return similar results.

**Comment by cofiem** [comment]
The problem is that the current query includes a join to the tags table, so the audio_event is included equal to the number of tags.

code is here https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/audio_event.rb#L113

**Comment by atruskie** [comment]
@jwim1 can't do data processing...

He'd like the tag ids in separate columns. So this essentially means the following columns need to be added:

- common_name_tag_id
- species_name_tag_id
- other_tags_ids

**Comment by jwim1** [comment]
Do unfair..

**Comment by jwim1** [comment]
= So unfair
