### ISSUE TITLE
Allow redirect url after logging in

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#205]
See [devise setup](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/store_location.rb).

See also #114

**Comment by atruskie** [comment]
Got a desired QSP? I'm setting the client up to work with it now

**Comment by cofiem** [comment]
Devise seems to use the QSP [`user_return_to`](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/store_location.rb#L54)

**Comment by cofiem** [comment]
See also https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in

**Comment by cofiem** [comment]
QSP is `redirect_to`

**Comment by cofiem** [comment]
Changes:
 - Adding `redirect_to=/somewhere` to any `/errors/*` page or `/my_account/sign_in` will redirect to that path after a user signs in.
 - `redirect_to` will only redirect to `/<path>?<querystring>`. The domain is ignored. (e.g. `/errors/unauthorised?redirect_to=http://google.com/somewhere?key=value` will redirect to `/somewhere?key=value` within the app).
 - the links on the error pages will have `redirect_to` QSP appended if it is set.
