### ISSUE TITLE
Separate api endpoints from Rails view urls

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#209]
It is becoming difficult to manage the separation of API and Rails view rendering in the same controllers. Separating these out into and  `/api` namespace will relieve this, and provide a clear path towards a more consistent API.

**Comment by atruskie** [comment]
:+1:  all good for me.

I don't like that this has to happen (from a RESTful API design point of view) but if it makes things simpler go for it

**Comment by cofiem** [comment]
Currently, this would not be worth the effort it would require.

**Comment by atruskie** [comment]
Just refresh my memory here, why was this getting hard to manage?

**Comment by cofiem** [comment]
it was getting difficult due to the branching logic for Rails views / REST API. However, I forget the exact problems, and from what I can see, it would not really gain much at the moment.
