### ISSUE TITLE
Feature suggestion - Grouped tag counts per user

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#214]
Suggested by @JessCappadonna

User profile page should offer a breakdown of tag counts per user - so they can see how many of which species they have annotated.

This idea may be extended to the global stats page:
 - Top users (privacy issues)?
 - Most popular tags?

**Comment by cofiem** [comment]
Sensible suggestions. This would need #162 and a re-work of the queries used to populate the global stats page. I agree that there are potential privacy issues around users names.

**Comment by cofiem** [comment]
Not going to do top users or most popular tags on stats page.

Also have not done caching.
