### ISSUE TITLE
Encode file Audio file names with UTC time zones

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#22]
At the moment we encode the creation date of audio files in their filename like so (with the 10+ time zone): 

    original_audio/63/631ed7d5-ef52-4aa6-9062-ffdd41256930_100810-1200.mp3

There are 220K files named this way due to legacy reasons.

The associated record for this file stored in the  database under `recorded_date` is 

    2010-08-10 02:00:00 (UTC)

While the `config.timezone` rails setting is on there is no problem. However, if we ever want to change the timezone we will no longer be able to reference the bulk of the files.

Suggested tasks:
 - [x] Encode new files with UTC dates (disambiguate with `Z` suffix on time)
 - [ ] Cleanup old files (convert their datestamps to UTC)
 - [x] When checking for the presence of an audio file, check for both the `config.timezone` variant and the UTC variant

**Comment by cofiem** [comment]
See https://github.com/QutBioacoustics/baw-private/issues/81
