### ISSUE TITLE
Change maximum media request size

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#221]
We have some (exactly 6 actually) `audio_events` that are longer than the maximum limit for media downloads (media maximum = 120s, longest audio event = 161s). When these events are shown in the library, they can't be shown.

Proposed: change the maximum allowed media duration to 180s.

**Comment by cofiem** [comment]
e.g.

GET /audio_recordings/138285/media.png?audio_event_id=10586&end_offset=228&start_offset=98

````
{
"audio_event_id"=>"10586", 
"end_offset"=>"228", 
"start_offset"=>"98", 
"format"=>"png", 
"controller"=>"media", 
"action"=>"show",
 "audio_recording_id"=>"138285"
}
````

````
A BawAudioTools::Exceptions::SegmentRequestTooLong occurred in media#show:

  Requested duration 130.0 (98.0 to 228.0) is greater than maximum (120.0).
  lib/modules/api/media_metadata.rb:182:in `check_duration_defaults'
````

**Comment by cofiem** [comment]
Old:
 - `cached_audio_defaults.max_duration_seconds` = 300.0 (5 minuntes)
 - `cached_spectrogram_defaults.max_duration_seconds` =  120.0 (2 minuntes)

New:
 - `cached_audio_defaults.max_duration_seconds` = 300.0 (5 minuntes)
 -  `cached_spectrogram_defaults.max_duration_seconds` =  180 (3 minuntes)
