### ISSUE TITLE
User endpoint shows way too much information

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#223]
User endpoint needed for some site functions (particularly associating user names with ids).

Currently a `GET http://staging.ecosounds.org/user_accounts/85` with a non-admin user (logged in, returning info for a different user) returns:

```
{
    "id": 85,
    "email": "j.wimmer+nqb502@qut.edu.au",
    "user_name": "NQB502",
    "authentication_token": "yesTheFullAuthTokenWasReallyReturned",
    "invitation_token": null,
    "created_at": "2011-03-24T18:08:08.000+10:00",
    "updated_at": "2011-03-24T18:08:08.000+10:00",
    "roles_mask": 2,
    "image_file_name": null,
    "image_content_type": null,
    "image_file_size": null,
    "image_updated_at": null,
    "preferences": null,
    "tzinfo_tz": null,
    "rails_tz": null,
    "last_seen_at": null
}
```

Security for this endpoint should be updated.

If *not* the current user or admin, returned fields should be restricted to:

- id
- user_name
- image_url (not present atm?)
- tzinfo_tz
- rails_tz
- last_seen_at

**Comment by cofiem** [comment]
Oh, damn. Yeah, I haven't looked at that endpoint for at least a year, probably.
That's probably a dump of all the user fields :(
