### ISSUE TITLE
Inconsistent Date and Time encodings in audio files

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#23]
The rails app uses the following format strings to encode a date into an audio file name ([here](https://github.com/QutBioacoustics/baw-server/blob/master/app/models/audio_recording.rb#L66) ):

    :date => a.recorded_date.strftime("%Y%m%d"),
    :time => a.recorded_date.strftime("%H%M%S"),

The majority of the files we have are encoded with a different format string:

     "%y%m%d"
     "%H%M"

Suggested changes
- [x] temporarily check for both formats
- [x] save new files with new format
- [ ] at some point create a script to cleanup old format
- [ ] eventually remove redundant code
- [x] all file name encoding and decoding should be refactored into a single testable unit

**Comment by cofiem** [comment]
See https://github.com/QutBioacoustics/baw-private/issues/81
