### ISSUE TITLE
Weird notification bug

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#242]
A notification is showing on the main website page that simply states 'true'. Happens when a session is expired. See screenshot:

https://gyazo.com/3efef10f471c57218a0b434c2f28e911

**Comment by atruskie** [comment]
Finally worked out the cause of this: https://github.com/plataformatec/devise/issues/1777

**Comment by AbeCole** [comment]
If your echoing out the message and having an issue with this 'true' text being displayed, I used the following solution to reduce the standard flash array to only items whose value is a String:

flash.select { |m| m[1].is_a?(String) }

**Comment by atruskie** [comment]
Thank you for the tip.

However, we already fixed this in a branch, see: https://github.com/QutBioacoustics/baw-server/pull/313/commits/93b47f97a2a1ed0f89c4b03da599c9a3d7e4ad6a
