### ISSUE TITLE
An ArgumentError occurred in media#show

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#252]
Can reproduce this as a **non-Admin** user only. These resource requests are generated by the _Library_ page.

@YvonneP noticed this. 

Production version `v0.18.0-0`.

```
An ArgumentError occurred in media#show:

  No projects provided.
  lib/modules/access/core.rb:147:in `validate_projects'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.ecosounds.org/audio_recordings/213461/media.json?audioEventId=13380&endOffset=655.724&startOffset=650
  * HTTP Method: GET
  * IP address : [CENSORED]
  * Parameters : {"audioEventId"=>"13380", "endOffset"=>"655.724", "startOffset"=>"650", "format"=>"json", "controller"=>"media", "action"=>"show", "audio_recording_id"=>"213461"}
  * Timestamp  : 2016-02-17 15:02:39 +1000
  * Server : web-01
  * Rails root : [CENSORED]/production/releases/20160216074841Z
```

```
-------------------------------
Backtrace:
-------------------------------

  lib/modules/access/core.rb:147:in `validate_projects'
  lib/modules/access/level.rb:13:in `projects'
  lib/modules/access/check.rb:69:in `can_any?'
  app/models/ability.rb:167:in `block in to_audio_recording'
  app/controllers/application_controller.rb:122:in `auth_custom_audio_recording'
  app/controllers/media_controller.rb:67:in `authorise_custom'
  app/controllers/media_controller.rb:15:in `show'
  app/controllers/application_controller.rb:487:in `set_then_reset_user_stamper'
```

**Comment by cofiem** [comment]
Problem is obvious - this site is not in a project. It is an orphan. Just put it into a project using https://www.ecosounds.org/projects/<project_id>/edit_sites and all should be fine.

**Comment by atruskie** [comment]
Fair point ~~will do~~. I can't work out what this site is, so instead I'm going to un `Is_reference` the 98 audio_events in that site.

Should we code for this?
OrphanedSiteException maybe?

However, this is an error with the database that only occurred because of data import.

**Comment by cofiem** [comment]
Adding a special Error for this is fine. Even though site should not be orphaned, it is quite possible. 

Error will be added in [custom_errors.rb](https://github.com/QutBioacoustics/baw-server/blob/develop/lib/modules/custom_errors.rb), probably as a subclass of `StandardError`.

**Comment by atruskie** [comment]
:+1:
