### ISSUE TITLE
Add `overall_size_bytes` field to job model

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#256]
The `AnalysisJobs` model currently tracks aggregate statistics for the saved search it executes like `overall_count` and `overall_duration_seconds`.

Feature: add a new field that aggregates the `data_length_bytes` field from the saved search.

Name options:
- `overall_size_bytes`
- `overall_data_length_bytes` 

Related to #191

**Comment by cofiem** [comment]
Justification? Is this only for displaying stats, or will the information be used for some kind of action?

**Comment by atruskie** [comment]
Mainly for stats. Realizing this prototype interface: https://gyazo.com/c9784b0aeb7983ee6e64e156ed34ad04

Additionally, we'd like to report count/duration/size analyzed stats at a larger scale. It'd be good to track this information now before the system is used in earnest.

**Comment by cofiem** [comment]
Sounds good. 

Maybe make a separate issue for tracking overall stats? Would this be part of the generic stats table idea?

**Comment by atruskie** [comment]
Where practical we hope to encode stats in schema explicitly. This minor suggestion is not part of generalized stats idea (for which issue is coming - nailing down a few things offline first).

**Comment by atruskie** [comment]
:+1:
