### ISSUE TITLE
Add calculated field recorded_end_date to AudioRecording's filter options

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#261]
Request: and calculated field `recorded_end_date` to the filter options in the `AudioRecording` model.

This field would be defined as:

    recorded_end_date = recorded_date + duration_seconds

This field will be useful in completing the saved search story. E.g. find all recordings that have content past a certain date.

**Comment by atruskie** [comment]
:+1: - more complicated than I expected but very cool. Cheers.

**Comment by cofiem** [comment]
:smiley: yeah, I had to use arel to construct the query. 

It's like there's a gremlin in the system that sees your issues, and fixes them.....

**Comment by cofiem** [comment]
Be aware that that dates you send must be in utc, and prefer using `Z` over `+0000`. I had trouble getting some offsets and time zone names to parse correctly, since the filter system doesn't use ActiveRecord's datetime conversion.

**Comment by atruskie** [comment]
hmm... that could represent a serious problem. Does this affect all date fields used in all filters? Or just this custom one?

**Comment by cofiem** [comment]
I think this would affect all date fields in filters (other parts of API should be fine).

**Comment by atruskie** [comment]
One last question: does it throw an error with bad timezones it fails to parse or does it silently continue?

**Comment by cofiem** [comment]
I hate to say it, but I think it silently continues with whatever it thought the datetime is :disappointed:

**Comment by cofiem** [comment]
This... probably... definitely needs a bit more work...

**Comment by atruskie** [comment]
It is a separate issue, tracked in #263
