### ISSUE TITLE
Expose `sites.tzinfo_tz` field in API

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#262]
Please expose the `txinfo_tz` field from the `Site` model in the REST API.

This will be needed in the future to show timezone specific formatting for dates and times of audio recordings, date filters, and in the visualization tool.

**Comment by cofiem** [comment]
Both [sites](https://github.com/QutBioacoustics/baw-server/blob/develop/db/structure.sql#L481) and [users](https://github.com/QutBioacoustics/baw-server/blob/develop/db/structure.sql#L608) might have time zone info stored.

They both have `tzinfo_tz` for [TZInfo](http://tzinfo.github.io/) and `rails_tz` for [ActiveSupport::TimeZone](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html).

Please confirm which information you want to use.

**Comment by atruskie** [comment]
It seems `tz_info` is already exposed for user profile... at least in the `my_account` endpoint.

As far as I can tell http://momentjs.com/timezone/ works with tz_info and rails_tz is just a subset of that info? In which case just `tzinfo_tz` should be sufficient.

Perhaps best choice is to include a sub object in similar form to this: http://metaskills.net/2012/08/05/rails-moment-js-and-time-zones/

And if sub object chosen, name the field `timezone_information`.

**Comment by cofiem** [comment]
I decided to go with the sub object to be clear about the values. Schema:

    "timezone_information":{
        "identifier_alt":"Sydney",
        "identifier":"Australia/Sydney",
        "friendly_identifier":"Australia - Sydney",
        "utc_offset":36000,
        "utc_total_offset":39600
    }

It will return 

    "timezone_information":null

if there is no timezone information available.
