### ISSUE TITLE
Allow markdown in description fields

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#264]
Suggestion from @JessCappadonna

Allow at least line breaks, but ideally markdown in project and site descriptions. Nothing fancy, no preview or WYSIWYG, just plain text accepted, markdown rendered. 

Using Kramdown would be the best choice.

http://thecrentist.com/setting-up-rendering-markdown-highlighting-ruby-on-rails/

**Comment by cofiem** [comment]
Both `description` and `notes` for `site` and `user` will include a `*_html` field. If you don't want `notes` included, just let me know.

**Comment by atruskie** [comment]
Where we have used `notes` for `site`s in production, it has been to store structured data - JSON for 243/244 rows `WHERE NOT notes IS NULL`. Therefore I'm going to veto `site.notes` getting the markdown treatment.

I assume you mean `projects` and not `users` in you previous post.

**Comment by cofiem** [comment]
yes, sorry, `projects` :stuck_out_tongue_closed_eyes:

**Comment by cofiem** [comment]
Ok, remove markdown processing from `site.notes`. 

For consistency, remove from `project.notes` as well? Although, projects expose the notes field as editable. What would you prefer? Either:
- make project.notes field not editable and not process markdown?
- keep project.notes field editable and keep markdown processing?

**Comment by atruskie** [comment]
Annoying `project.notes` has been exposed to users. As such I think we're going to have to leave it that way because there's actually text in those fields... even though I presume user's think the text is lost

The other option would be a new issue to either:
- collapse notes into the description
- convert existing notes to JSON
