### ISSUE TITLE
Regression: harvest.yml and harvest instructions not available to owners

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#269]
This feature request: https://github.com/QutBioacoustics/baw-server/issues/228#issuecomment-121456985

Fixed by this commit: https://github.com/QutBioacoustics/baw-server/commit/618e724b33fb5140ba934b83a85c614c2822c402#diff-e9c04d21b8c4d777e4231c4c6ce5f8cbR75

Seems to have been regressed. Cannot find equivalent functionality in code or in behaviour. 

Noticed by @JessCappadonna

**Comment by cofiem** [comment]
The Upload instructions are very out of date: https://github.com/QutBioacoustics/baw-server/blob/develop/app/views/sites/upload_instructions.html.haml
