### ISSUE TITLE
Analysis Result file list `path` and `name` semantics

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#272]
Take the following snippets of valid JSON returned from https://staging.ecosounds.org/analysis_jobs/system/audio_recordings/187684/ and https://staging.ecosounds.org/analysis_jobs/system/audio_recordings/187684/Towsey.Acoustic:

```json
{

    "path": "/",
    "name": "/",
    "type": "directory",
    "children": [
        {
            "path": "log.txt",
            "name": "log.txt",
            "type": "file",
            "size_bytes": 196054,
            "mime": "text/plain"
        },
        {
            "path": "Towsey.Acoustic.yml",
            "name": "Towsey.Acoustic.yml",
            "type": "file",
            "size_bytes": 1968,
            "mime": "application/x-yaml"
        },
        {
            "path": "Towsey.Acoustic",
            "name": "Towsey.Acoustic",
            "type": "directory",
            "has_children": true
        }
    ]

}
```

```json
{

    "path": "Towsey.Acoustic",
    "name": "Towsey.Acoustic",
    "type": "directory",
    "children": [
        {
            "path": "Towsey.Acoustic/4c77b524-1857-4550-afaa-c0ebe5e3960a_20101012-140000Z__IndexGenerationData.json",
            "name": "4c77b524-1857-4550-afaa-c0ebe5e3960a_20101012-140000Z__IndexGenerationData.json",
            "type": "file",
            "size_bytes": 217,
            "mime": "application/json"
        }
        …
    ]
}
```

The following inconsistencies should be addressed:

- do we consider the base results directory its own filesystem (first snippet)?
  1. if so, then the root of the file system should have `path == '/'` and `name == '/'`
  2. if not, then shouldn't both `path` and `name` should be blank?

Assuming yes on the previous point:

-  then all `path` attributes on all children should be proceeded by  `/` (slash) otherwise we're using model _i_ for root node and model _ii_ for child nodes

Thoughts?

One last point: the `path` field seems a little redundant in our datasets. Perhaps `path` could be removed for all `file` type objects as the full path can be determined by parent directory `path` + `filename`

**Comment by cofiem** [comment]
From discussion:
- Treat base results directory as virtual filesystem root. Therefore add slash before directory `path` and attribute. The name for the base directory is `/`.
- Remove `path` attribute for `file` objects.

**Comment by cofiem** [comment]
Both `description` and `notes` for `site` and `user` will include a `*_html` field. If you don't want `notes` included, just let me know.

**Comment by atruskie** [comment]
:+1:
