### ISSUE TITLE
Convert project.notes into hidden machine-readable field

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#273]
Project.notes should be converted into a machine-readable field similar to sites.notes.

See #264 

This will involve:
- [x] Combining `notes` into `description`
- [x] remove text box from project edit page

**Comment by atruskie** [comment]
Manually deleted content  of `notes` field on these projects, and appended the content onto the `description`.

```
1017
1023
1024
1026
1031
1036
1037
1038
1041
1047
1055
```

**Comment by cofiem** [comment]
:tada: oh, righto then, that was all?

Well, I'll remove that field from the project edit page then.

**Comment by atruskie** [comment]
Yeah only a few had notes that had been changed. We've not used project notes for anything officially. 

Real easy cut-paste edit in pgAdmin's table editor

**Comment by cofiem** [comment]
Should staging also be cleaned up?

**Comment by atruskie** [comment]
Yeah, I checked; no records on staging have non-empty notes.
