### ISSUE TITLE
Need to expose analysis results' audio recordings

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#274]
Analysis jobs produce  results. For example `analysis_job.id == 1` may have results for recordings
`123,456,9439493,213131,122333,...`. It is quite reasonable that there could be 50K folders in the `.../analysis_results/1/` folder (one of our projects actually has that many recordings).

To expose results to users, so they can look/download/load up into tools, they need to be able to choose a recording to show the results. Recording IDs that are in the job are not guaranteed to follow any pattern (they are not sequential, often not contiguous). 

**Currently, the information for which audio recordings are part of a job is not tracked anywhere. These IDs are also not accessible via any part of the API**. Whatever solution chosen needs to support paging the results (i.e. some form of offset and limit).The following possible solutions exist:

1. native dir enumeration (i.e. `Dir.entries`)
  - pros: simplicity, extend virtual file system concept already used for analysis results
  - cons: directory listing for even a few hundred files is very slow. This effect is made worse because we rely on `noac` (no client cache) to ensure our nfs shares remain performant. Most importantly, I can't find a ruby API to page results.
1. tracking table
  - we'd use the job items concept from [here](https://github.com/QutBioacoustics/baw-server/issues/192#issuecomment-189828775) - specifically the (push+tracking table) idea
  - pros: next simplest idea, reuse a concept we're planning to make. Supports paging.
  - cons: this table could end up being massive (n^2 perf profile). We'd need to store the records permanently.
1. re-executing the saved saved search query
   - pros: possibly simple. we don't have to store anything. also supports paging.
   - cons: the results of the search could change when reexecuting. inconsistent results. On very large result sets the query time could prove to be prohibitive. Also the only item here that would return results for analysis results folders that don't exist yet.
1. caching saved search audio recording ids in simple binary manifest in `.../analysis_results/1/manifest.bin`
  - pros: divorced from database, storage of data isolated to analysis_jobs folder. essentially a cached `ls`
  - cons: would need to read and parse a file (very quickly) on every request - file could easily reach several hundred KB in size.
1. use swift (object store)
  - pros: it is made for this use case - hundreds of thousands of small files. It also supports paging.
  - cons: would introduce another dependency in our system. We'd likely need a fallback for disk based access anyway.

I'm currently unsure what the best path forward is.

Quick and dirty: option 1. and flag this as a potential future issue. :tada: technical debt.

Ideal: support 5. with a fallback for disc access based on 2.

Probably need to go with 2. Should be mediumly scalable.

**Comment by cofiem** [comment]
See also [existing batch job processing programs](https://github.com/QutBioacoustics/baw-server/issues/192#issuecomment-193122568).

**Comment by atruskie** [comment]
Another dimension I didn't realise until now: analysis results are wisely stored by the uuid and by our standard uuid partitioning scheme. I had incorrectly assumed results were stored by the `audio_recording.id` integer as the name of the folders.
