### ISSUE TITLE
Standardize secondary navigation

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-server#275]
The secondary navigation can be confusing. The main confusion from the links on the left stems from two parts: a) they change and disappear based on context and b) they mix actions with navigation. By removing all actions from the left navigation it will largely be able to remain the same despite the current context. Actions (like _edit_, _new_, _delete_, etc...) will move into the right hand column.

All links on the left will be global unless descending into a hierarchy, in which case contextual navigation links will be shown in groups. Icons will also be added to the left menu.

```
New navigation (left) menu:
- (home) Home
- (sign-in) Log in / (user) My Profile 
- (user-plus) Register / (square-o) My Annotations
- (globe) Projects 
- (server) Audio Analysis
- (book) Library
- (table) Data Request
- (envelope) Send Audio
- (bug) Report Problem
- (line-chart) Website Statistics

Other icons for standard use:
- (bar-chart) visualize (project & site) [new name: _Data Visualisation_]
- (tag) tags
- (square-o) annotations
- (play) Only used when immediate audio is played 
- (headphones) Any link that takes to a listen page and must have text to say "listen"
- (map-marker) sites
- (download) Download 
```

Related [https://github.com/QutBioacoustics/baw-client/issues/260] - should be released at the same time.

**Comment by cofiem** [comment]
@atruskie were there any design ideas / prototypes for the right hand actions list?

**Comment by atruskie** [comment]
Yes, I have prototype the design in the [baw-client custom-job-ui branch](https://github.com/QutBioacoustics/baw-client/tree/custom-job-ui). Screenshots below.

- https://gyazo.com/e8389135c853ec93c53980e7131e708c
- https://gyazo.com/7dba321aea4ebef9509781f620b6baa0
- https://gyazo.com/281e0487d95fa478e36932f5ab9579ea
- https://gyazo.com/4a48392860e274e24d0c0550814e29be

Those layouts aren't perfect
- I didn't put in the full left hand menu (wasn't settled on at that point)
- no indentation in left hand menu (still an unsolved problem)
  - need shorter names or wider columns
  - I _think_ we want to avoid more than one layer of nesting. e.g. for sites (note how site isn't nested under project):
    - home
    - projects
    - sites
      - **details**
    - ...(other)
- we're considering removing the title in the left hand column (no need to be duplicated)
- we need a consistent language for CRUD
  - details
  - new
  - edit
  - delete

I think what would be best to proceed with issue is to prototype the project and site page menus first, take snapshots, then meet back here discuss design and then change everything else (inc. client pages QutBioacoustics/baw-client#260)
