### ISSUE TITLE
Allow query string filter parameters to be used on field_mapping attributes

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#286]
In the [API spec](https://github.com/QutBioacoustics/baw-server/wiki/Rails-API-Spec---Filtering), query string parameters (QSPs) are allowed to be used for filtering using equality only semantics.

It does not appear this functionality has been implemented for field mappings (which seem to me to be virtual fields). Other attribute types seem to work fine.

Example cases:

| Compare Type | Request | Works? |
|--------------------|-------------|----------|
| String  | `GET /scripts?filter_name="simulate work"` | :+1: | 
| Number | `GET /scripts?filter_version=2` | :+1: | 
| Field Mapping | `GET /scripts?filter_is_last_version=true` | :-1:  | 
| Number | `GET /audio_recordings/234234/audio_events?filter_start_time_seconds=0.1161` | :+1: | 
| Field Mapping | `GET /audio_recordings/234234/audio_events?filter_duration_seconds=1.8112` | :-1:  | 

_`is_last_version` is a field mapping from [here](https://github.com/QutBioacoustics/baw-server/commit/4db980b4531b65d47e730247b0e0c6b7067ec239#diff-9cacd63540753d6929377d6cb58210cbR107)_

The failed requests currently fail with a 500 because the field is passed through to the database (it shouldn't be allowed to do that either) and this error is raised: `ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column audio_events.duration_seconds does not exist`

Example source object for reference:
```
{
"id": 2,
"name": "simulate work VERSION 2",
"description": "simulates running an analysis",
"analysis_identifier": "SIMULATE_WORK",
"version": 2,
"group_id": 1,
"creator_id": 1,
"created_at": "2016-02-18T05:58:05.465Z",
"executable_settings": "# nothing\r\nsomeSettings:\r\n key: value\r\n aList:\r\n - a\r\n - b\r\n - c",
"executable_settings_media_type": "text/plain",
"is_last_version": true,
"is_first_version": false
}
```

Please add support for filtering by QSP for field mappings.

**Comment by cofiem** [comment]
I've almost got this working. Then #287 should work

**Comment by atruskie** [comment]
Cool, lots of lines removed. Nice work. :+1:

**Comment by cofiem** [comment]
Ha, yup. Much of the added stuff is tests, too.
