### ISSUE TITLE
Deleted audio events are being returned in download annotations link

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#302]
Reported by @KarlinaInd, annotations downloaded in the CSV format include those that have been deleted. THIS SHOULD NOT HAPPEN.

Confirmed by downloading a fresh CSV and also querying the database. May be related to #292 

Update: this is likely caused by the `csv_query` method using the AREL table over the active record query with the default non-deleted scope. https://github.com/QutBioacoustics/baw-server/blob/develop/app/models/audio_event.rb#L119

**Comment by cofiem** [comment]
:dash: yup, that's likely the issue

**Comment by JessCappadonna** [comment]
Remember soon after I started I showed you guys links in the excel spreadsheet that no longer had annotations as well.... it was never resolved so I just delete them whenever I download the CSV
