### ISSUE TITLE
Release 1.1.0 UI tweaks

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#322]
- Project tile card:
   - CSS break lines on words
   - add extra lines for descriptions
   - render or strip markdown in description
 - Project show:
   - List owners
- Project permissions:
  - page resets after changing permissions
  - page by numbers is useless (page by alphabet? add a search?)
- Site show:
  - list parent project in the title (from https://github.com/QutBioacoustics/baw-client/issues/296) cc @towsey
- Sidebar ordering for narrow pages, ensure actions come before content

... more to come

**Comment by atruskie** [comment]
I'm part way through this issue, can I get feedback on this:

Addressing _list parent project in the title_, old style: https://gyazo.com/0f0e7c3141bac8784de82db4d44933b5

New style: https://gyazo.com/ba9eaad32b042af6ea2ec9c7df034625

@towsey and @JessCappadonna in particular, what are your thoughts?

**Comment by towsey** [comment]
Once you know that the folder sign stands for a project then it is clear. Could you not add the word "Project" in front of title, i.e. "Project: Title"

I like the site description. Makes things clear.

**Comment by atruskie** [comment]
@towsey - how's this: https://gyazo.com/90d518dd104e5ef78d08fb781b98efcd ?

**Comment by towsey** [comment]
I think that is better. Could also put "Site:" in front of site name for additional clarity.

**Comment by atruskie** [comment]
Closed via commits:
- https://github.com/QutBioacoustics/baw-server/commit/a02cb94d46a53264118d2f084200c656834eabce
- https://github.com/QutBioacoustics/baw-server/commit/e009a23d1ab5b96588c9ef184afca1e678133582
- https://github.com/QutBioacoustics/baw-server/commit/e53620ef6d9f58c8d5fc0364f2027aab60c2b127
- https://github.com/QutBioacoustics/baw-server/commit/da2dfdb9c2233131b6449a8f6dfefaaf9d417bad
- https://github.com/QutBioacoustics/baw-server/commit/489e73cef885724953dacc259d2ebeb9f577b975
- https://github.com/QutBioacoustics/baw-server/commit/6eaa40b6df608eaaf1676ea07d0cfeb05130c73f
