### ISSUE TITLE
Dataset page, placeholder text time format

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#39]
The expected time format for the time fields on the dataset page is currently not shown or hinted at.

Suggestion: add placeholder text to inputs to show time format. Also add help hints...

**Comment by cofiem** [comment]
Although the dataset page no longer exists, this is still relevant for the planned 'filter' page.

**Comment by cofiem** [comment]
Although the advice still applies, waaaay out of date...
