### ISSUE TITLE
Json responses need to be tidied up - not all information should be returned

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#61]
e.g. `notes`, `latitude` and `longitude` for Sites.

**Comment by cofiem** [comment]
Completing the filter endpoints and converting custom endpoints to standard ones will address this issue.

**Comment by cofiem** [comment]
This is addressed for the major endpoints. There are some endpoints that still need to be converted (e.g. the custom endpoints for `audio_recordings`), however these are not so important.

**Comment by atruskie** [comment]
Can you create issues for any endpoints that do not use standard format please? Even if not important, nice to track in terms of visibility.

**Comment by cofiem** [comment]
As far as I can see, only two endpoints do not conform to the API spec: the media and analysis endpoints, see #255. Everything else seems to be using the standard api.

**Comment by atruskie** [comment]
:+1: thanks. Really good to see everything standard. I'm creating more and more reusable patterns because of this.
