### ISSUE TITLE
Add saved_searches model, plus associated changes

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#64]
This is a complicated change.

 - The current datasets table should be the saved_searches table
 - The relationship is a saved_search has_many datasets
 - Progress will eventually be linked to a dataset
 - sites, projects, jobs will be linked to the saved_search
 - renamed controller and create a new controller
 - update tests
 - create new tests

This is still not optimal, as saved_searches can be modified. This may mean that the dataset a job refers to has changed. It can also mean that a saved_search does not reflect the content of an older dataset. Other options are to have immutable saved_searches, however the dataset may or may not be able to be re-generated.

This is a rather important and very difficult issue.

**Comment by cofiem** [comment]
See #194 #193 #189

**Comment by atruskie** [comment]
This issue is out of date. Closing - refer to linked issues above for more up to date specs.
