### ISSUE TITLE
Error in obfuscation of lat/long

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#91]
Reported by Dez:
>  Latitude – Longitude appears to be randomising before obfuscating. This is producing a misplacement of the Lat-Long greater than the code originally was set for of 10m. The error appears to be up to 100km

- [x] Double check the unit tests - we're meant to be rounding to nearest ±20m
- [ ] Possibly: store the jittered location so it does not move around
  - may not need to once it jitters correctly (the moving effect would be small)
- [ ] Possibly: remove jitter for users with write permissions

Confirmed by @antmt

**Comment by cofiem** [comment]
Fixed in cf1a88bfbde979015a62ef5c9b938c3787245ca2
