### ISSUE TITLE
Broader Permission categories for Projects (and all sub-securables)

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#99]
Two new permissions:

- Logged-in access
    - should be able to `read`, `write`, but not `own`
- Anonymous access
   - should be able to `read`, `write`, but not `own`

- Only owners/creators can modify the above permissions

**Comment by cofiem** [comment]
@atruskie question: which api endpoints / controller actions can a guest user (a user who is not logged in) or a logged in user access? We should arrange a time to go through the `ability.rb` file to ensure the access is as expected for the new anon/logged in permissions.

For example, can a guest user list (`/index`) or view (`/:id`) analysis jobs?

**Comment by atruskie** [comment]
I've updated the [permissions spec](https://github.com/QutBioacoustics/baw-server/wiki/Permissions) on the Wiki. It should answer most questions. If not we can discuss further.
